### ISSUE TITLE
Versionar perguntas

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#16]
A idéia é podermos versionar as perguntas para que seja simples alguém enviar uma idéia ou alteração.
Além disso, podemos usar para fazer algum tipo de build automático.

Pensei em coloca-las no minhacps/votasp mesmo, o que acham?

As perguntas até agora estão dessa forma, como @wab030 enviou no discord: 
[Mob_Questoes_Vota_SP.txt](https://github.com/Minhacps/votasp/files/2043183/Mob_Questoes_Vota_SP.txt)

**Comment by victorperin** [comment]
Estava pensando em criar um arquivo `PERGUNTAS.md` aqui nesse repositório, com a seguinte estrutura:
```
1- Uma pergunta?
2- Outra pergunta?
```
Com isso, conseguimos versionar e ainda manter as perguntas simples para quem não manja de programação para fuçar.

Depois podemos fazer um script que busca essas perguntas durante o build da api.

O que vocês acham?
@bwowk e @wab030 principalmente.

**Comment by brunowowk** [comment]
Acho uma ótima ideia. Assim o processo fica mais transparente e colaborativo.

**Comment by victorperin** [comment]
Só um update, estava conversando com o @gabriellira e achei melhor mudar para isso aqui:
```
1 | Categoria | Uma pergunta?
2 | Categoria | Outra Pergunta?
```

Você concorda também?

**Comment by victorperin** [comment]
Galera, despois de pensar um pouco melhor, concluí que podemos usar o formato table de markdown para colocar as perguntas em um formato visível. Do seguinte tipo:

```markdown
Id | Categoria | Pergunta
-- | --------- | --------
1  | Categoria | Uma pergunta?
2  | Categoria | Outra Pergunta?
```
O que daria esse output, que é bem visual e fácil de editar:

Id | Categoria | Pergunta
-- | --------- | --------
1  | Categoria | Uma pergunta?
2  | Categoria | Outra Pergunta?

Na API, podemos usar o pacote [mdtable2json](https://github.com/vzaccaria/mdtable2json) para transformar em um json usável. O código seria +- o seguinte:
```javascript
const md2json = require('mdtable2json')

const markdown = `
  -- | --------- | --------
  1  | Categoria | Uma pergunta?
  2  | Categoria | Outra Pergunta?
`

const results = md2json.getTables(markdown)

const json = results[0].json
```

Lembrando que a idéia, é que durante o inicio da api de questions, ele carregue esse markdown da url raw do github.

**Comment by wab030** [comment]
Só falta incluir MouseOver e Habilitada.


Id | Categoria | Pergunta | MouseOver | Habilitada
-- | -- | -- | -- | --
1 | Categoria | Uma pergunta? | Explicação 1 | Sim
2 | Categoria | Outra Pergunta? | Explicação 2 | Não

**Comment by victorperin** [comment]
Não acho que precisamos do item `habilitada`. É só remover a linha e não repetir o id.

Com relação ao `MouseOver`, acho que fica muito complexo colocar tudo na mesma linha. Talvez, quando criarmos essas descrições, podemos colocar em outra área (uma segunda tabela a baixo dessa ou num outro arquivo mesmo).
Minha preocupação é o github quebrar muito essas descrições e perguntas tornando difícil de ler.

Além disso, o nome `MouseOver` está meio estranho pra mim. O que você acha de chama-la de `descrição` ou algo do tipo?

**Comment by wab030** [comment]
@victorperin Podemos chamar de descrição sim. Coloquei mouse somente para entendimento mas me esqueci de mobile. Precisamos dar um jeitinho de apresentar essa descrição para algumas perguntas.

**Comment by victorperin** [comment]
Ok, vou criar uma issue sobre a descrição das perguntas e resolvemos isso no próximo presencial que fizermos.
Enquanto isso, vou mergear dessa forma.
