### ISSUE TITLE
Descrever arquitetura

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#2]
Descrever sobre a arquitetura seguindo a imagem:

![image](https://user-images.githubusercontent.com/903193/40364158-f93d35f4-5da7-11e8-8ba8-964a43549505.png)

Breve explicação sobre cada parte da arquitetura

**Comment by lai32290** [comment]
[Resultado](https://github.com/Minhacps/votasp-backend/blob/master/README.md)
