### ISSUE TITLE
Usuários podem descrições sobre a pergunta (mouseover)

### ISSUE THREAD

**Issue by wab030** [Minhacps/votasp#20]
Desenvolver a função mouseover para as questões. Quando o usuário passar o mouse sobre a questão uma explicação da questão deve ser exibida para questões mais complexas.

**Comment by mandyellow** [comment]
Estamos desenhando o mobile primeiro, coloquei logo depois do texto um ícone para o usuário ter mais informações sobre a questão. Podemos seguir da mesma forma no modelo desktop.

![09](https://user-images.githubusercontent.com/30158643/41375410-612efedc-6f2c-11e8-9f49-6c775316e51c.png)
