### ISSUE TITLE
Usuários podem compartilhar afinidade nas redes sociais

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#21]
O site, conteúdos do site e o resultado da afinidade devem ter a disponibilidade de compartilhamento nas seguintes redes sociais:

- Whatsapp

- Facebook

- Twitter

- Telegram

**Comment by victorperin** [comment]
Pensei em uma frase como:
`Minha afinidade com o candidato XPTO é 94%. Descubra a sua afinidade no votasp.org.br`

**Comment by wab030** [comment]
Perfeito.
