### ISSUE TITLE
Dados de cadastro dos usuários

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#22]
Para a realização do cadastro, os usuários devem informar:

- Nome: campo texto sem restrições
- Email: formato de e-mail
- Senha: campo texto sem restrições
- Cidade: dropdown list com as cidades do estado de São Paulo
- Se é candidato ou não
- Foto: opcional para usuário e obrigatório para candidato

**Comment by victorperin** [comment]
Está relacionado com a issue #39
