### ISSUE TITLE
Especulação pelo Sistema Proporcional

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#25]
Baixa prioridade. 

O sistema poderá dispor de uma aplicação que, através do Sistema Proporcional (eleitoral), indique qual candidato possivelmente seria eleito se o usuário votasse no candidato sugerido pelo sistema de afinidade.

Descrição da funcionalidade. 

1. Descobrir o [quociente eleitoral](https://pt.wikipedia.org/wiki/Quociente_eleitoral) dos dados armazenados no Vota SP --> quocienteEleitoral. 
2. Determinar quais são as coligações das eleições 2018. 
3. Calcular o número de eleitores e eleitoras do Vota SP --> numEleitores. 
4. Dividir o número de eleitores (quocienteEleitoral) pelo número de vagas no congresso nacional e na assembleia legislativa.
   4.1 Congresso nacional --> numVagasCongresso = (Total de votos da coligação)/70
   4.2 Assembléia do estado de SP --> numVagasAssembleia = (Total de votos da coligação)/93
5. Verifica e exibe quais foram os primeiros numVagasCongresso de cada coligação.
6. Verifica e exibe quais foram os primeiros numVagasAssembleia de cada coligação.

**Comment by victorperin** [comment]
Não entendi essa issue. Você pode descreve-la mais, por favor?

**Comment by wab030** [comment]
Talvez seja melhor explicar presencialmente. Mas não é prioritário.

**Comment by victorperin** [comment]
Tudo bem. Se quiserem, também podemos marcar um horario para o voice channel no discord. Pode ajudar um pouco. :)

**Comment by wab030** [comment]
SIm vamos marcar. Dia?

**Comment by victorperin** [comment]
Por mim qualquer dia a noite uhauhahua
O que acham de hoje a noite? Lá pelas 8 da noite acho um bom horario, mas posso mudar se quiser.

**Comment by wab030** [comment]
Dou aula hoje Victor. Só se for depois das 23.
