### ISSUE TITLE
Niveis de acessos de admins

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#26]
O sistema deverá dispor de níveis de acesso ao sistema para administradores. Consistindo em:
Nível 1 - normal: os usuários administradores deverão ser capazes de utilizar funcionalidades como gerenciamento de questões e formulários.
Nível 2 - conteúdo: os usuários administradores deverão ser capazes de gerenciar conteúdos que serão disponibilizados no site do Vota São Paulo.
Nível 3 - full: os usuários administradores deverão ser capazes de utilizar de ferramentas como gerência de conteúdo, questões, formulários e possuir acesso a funcionalidades técnicas do sistema e site.

**Comment by victorperin** [comment]
@VanessaAzuos18 isso me parece um pouco confuso.
Parece que está misturado o institucional e o app. Que funcionarão de maneiras bem diferentes.

Estou colocando essa issue para o institucional, pois ainda tem sentido o nivel de acesso para o blog.
Para o app, tudo é aberto e gerenciado diretamente pelo github. As questões serão editadas diretamente, de forma aberta, aqui no github.
