### ISSUE TITLE
Cores e fontes

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#27]
## Cores
Roxo: ![#57455c](https://placehold.it/15/57455c/000000?text=+) #57455c
Roxo claro: ![#7e798c](https://placehold.it/15/7e798c/000000?text=+) #7e798c
Amarelo: ![#feb557](https://placehold.it/15/feb557/000000?text=+) #feb557
Branco: ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) #FFFFFF

## Fonte
ASAP: https://fonts.google.com/specimen/Asap

**Comment by lai32290** [comment]
Roxo: ![#57455c](https://placehold.it/15/57455c/000000?text=+) #f03c15
Roxo claro: ![#7e798c](https://placehold.it/15/7e798c/000000?text=+) #7e798c
Amarelo: ![#feb557](https://placehold.it/15/feb557/000000?text=+) #feb557
Branco: ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) #FFFFFF

Font: ASAP

To colocando as cores só pra facilitar a visualização.

**Comment by wab030** [comment]
Font: ASAP

**Comment by notnotgabriel** [comment]
Linkando a fonte: https://fonts.google.com/specimen/Asap

**Comment by victorperin** [comment]
Editei a descrição da issue para ficar mais fácil. :)
