### ISSUE TITLE
Administrador/gerenciador de conteúdo

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#29]
CADASTRO:
O cadastro de administrador/gerenciador de conteúdo deve ser capaz de realizar cadastro no sistema informando o nome, email, senha e cidade.

FUNÇÕES:
Deve ser capaz de inserir, editar, excluir e promover conteúdos do site.

**Comment by victorperin** [comment]
Isso parece ser relacionado ao projeto institucional, certo?
Estou movendo para esse projeto.
