### ISSUE TITLE
Descrever o projeto VotaSP (Criar README)

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#3]
Tópicos:
- O que é o VotaSP
- Como vai funcionar?
  - Como candidatos vão responder as perguntas?
  - Como usuários vão responder as perguntas?
- Como vamos fazer o match?
- Como posso ajudar?
  - Desenvolvedores
  - Ajude a pressionar
  - Ajude com custos do servidor

**Comment by lai32290** [comment]
[Resultado](https://github.com/Minhacps/votasp/blob/master/README.md)
