### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#30]
O site deverá ter o monitoramento de acesso através da ferramenta Google Analytics que oferece várias funcionalidades como gráficos, dados estatísticos, origem de acesso e mais.

**Comment by wab030** [comment]
Podemos utilizar outra ferramenta também se vocês acharem mais interessante.

**Comment by victorperin** [comment]
Uma das alternativas que eu conheço é esse cara aqui:
https://matomo.org/

Até onde eu testei, cobre grande parte do que o Google Analytics cobre.
