### ISSUE TITLE
Página de Login (Com o auth0)

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#32]
Protótipo: https://marvelapp.com/6e384fb/screen/43225740

Pontos que notei que merecem atenção:
- Os botões de social login podem (e provavelmente vão) mudar. Então, tente deixar o mais fácil possível para que seja acrescentado ou removido opções. (O Auth0 deixa fácil fazer isso. Mas o layout tem que ser compatível)

![01](https://user-images.githubusercontent.com/30158643/41374965-08f5b8ec-6f2b-11e8-84e2-67ec739ff831.png)

**Comment by victorperin** [comment]
Atualizei a imagem que a @mandyellow atualizou.
@victormiguez da uma olhada pra ver se não tem nada diferente.

**Comment by victorperin** [comment]
A @mandyellow criou a issue no repo do app: https://github.com/Minhacps/votasp-app/issues/3
(Mas como o ideal é deixar todas as issues aqui nesse repo, estou movendo tudo o que ela colocou aqui.)

**Comment by victorperin** [comment]
![login-page](https://user-images.githubusercontent.com/30158643/40945616-0647de10-6830-11e8-95e9-6d096a25e04a.png)

**Comment by wab030** [comment]
Podemos incluir o Twitter e o Google como logon também?

**Comment by notnotgabriel** [comment]
Acho que o entrar pelo instagram não precisaria. Twitter, google e face são os principais na minha opiniao.

**Comment by victorperin** [comment]
A base de usuários de quem usa facebook e instagram é basicamente a mesma então inclui tantas pessoas.
Concordo com o @notnotgabriel e o @wab030.

- Facebook
- Google
- Twitter

**Comment by lguima** [comment]
O Twitter não fornece o e-mail, então não é possível identificar se o usuário já existe, duplicando-o.

Removemos a opção de login com Twitter.
