### ISSUE TITLE
Iniciar Questions API

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#33]
Estou inicializando a questions API usando NodeJS.

Usarei KoaJS e Jest para testes.

**Comment by victorperin** [comment]
O @bwowk conseguiu avançar com ela no minhacps/votasp-backend#14.

@gabriellira conversa comigo no discord quando você puder para eu te mostrar alguma outra coisa que podemos codar.

**Comment by gabriellira** [comment]
blz, @victorperin , to la no Voice Channel de back-end
