### ISSUE TITLE
Página Ranking/Resultados

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#35]
![07](https://user-images.githubusercontent.com/30158643/41374983-15799f48-6f2b-11e8-87fe-c88d969f60e4.png)

Importado da issue aberta pela @mandyellow no repo APP: https://github.com/Minhacps/votasp-app/issues/8

**Comment by mandyellow** [comment]
Atualizei a imagem.

O que mudou:
1- Barra de progresso para o usuário saber quantas questões estão respondidas;
2- Menu "Questões" para facilitar navegação entre as perguntas;

Marvelapp atualizado para facilitar entendimento (protótipo): https://marvelapp.com/6e384fb/screen/43225740

**Comment by lai32290** [comment]
Oie @mandyellow , eu vi que tem umas parte (tipo barra de progresso), diferente, entre a imagem e no marvelapp, eu vou seguir o do marvelapp, tudo bem?

**Comment by mandyellow** [comment]
Oi @lai32290, pode seguir o Marvelapp mesmo, ele tá mais atualizado!
