### ISSUE TITLE
 Página Menu Retrátil

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#36]
![menu-page](https://user-images.githubusercontent.com/30158643/40945661-41b94380-6830-11e8-9183-b95e0e4540a1.png)

Importado da issue aberta pela @mandyellow no repo APP: https://github.com/Minhacps/votasp-app/issues/7

**Comment by mandyellow** [comment]
#49 Essa issue está relacionada

**Comment by mandyellow** [comment]
Além das categorias, colocar um botão Home/Página inicial que volte para a página "Bem-Vindo" onde tem todas as categorias para que o usuário possa verificar as questões que foram respondidas.

**Comment by mandyellow** [comment]
Mudamos o projeto, esse menu retrátil não vai mais existir. Para mais informações segue o protótipo no Marvelapp: https://marvelapp.com/6e384fb/screen/43225740
