### ISSUE TITLE
Página Perguntas

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#37]
![04](https://user-images.githubusercontent.com/30158643/41441303-66b23108-7008-11e8-8dbc-13ff93564541.png)

![05](https://user-images.githubusercontent.com/30158643/41441304-66d644ee-7008-11e8-8832-97b7e9168f7c.png)

Importado da issue aberta pela @mandyellow no repo APP: https://github.com/Minhacps/votasp-app/issues/6

**Comment by mandyellow** [comment]
Atualizei a imagem.

O que mudou:
1- Não existem mais categorias;
2- A navegação das questões ficará no menu retrátil e terão as 40 questões.
3- Botões de "Pular" e "Finalizar";
4- Não existe mais "neutro" nas alternativas.

Protótipo: https://marvelapp.com/6e384fb/screen/43225740

**Comment by mandyellow** [comment]
Fiz algumas alterações nessa página, colocando aqui para abrir as discussões sobre isso no sábado.

Alterações:
1- Alternativas e alternativa selecionada em mais evidência
2- Botão de finalizar só aparece quando atinge a quantidade mínima de questões
3- Barra de progresso com menos evidência

![04](https://user-images.githubusercontent.com/30158643/41441303-66b23108-7008-11e8-8dbc-13ff93564541.png)

![05](https://user-images.githubusercontent.com/30158643/41441304-66d644ee-7008-11e8-8832-97b7e9168f7c.png)
