### ISSUE TITLE
Página Inicial

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#38]
![app-mobile-page-03](https://user-images.githubusercontent.com/30158643/41195695-f14cc6e2-6c08-11e8-97f2-1d5ad754a08a.png)

Importado da issue aberta pela @mandyellow no repo APP: https://github.com/Minhacps/votasp-app/issues/5

**Comment by notnotgabriel** [comment]
A @VanessaAzuos18 fez o html e css desta página. Vou Pegar o que ela já implementou e componentizar no react.

**Comment by mandyellow** [comment]
Precisamos pensar melhor no conteúdo dessa página para, talvez, dar uma explicação breve sobre como funciona o processo, mínimo de perguntas e quanto mais perguntas respondidas, maior a chance de ter um resultado mais preciso.

**Comment by mandyellow** [comment]
Atualizei a Imagem.

O que mudou:
1- Não existem mais categorias;
2- A barra de progresso agora está em todas as páginas para sinalizar para o usuário quantas questões ele respondeu;
3- Foi adicionado um menu retrátil no estilo do Google Calendar para fazer a navegação nas perguntas e sinalizar quais foram respondidas (imagem exemplo abaixo);

![app-mobile-page-06](https://user-images.githubusercontent.com/30158643/41195719-442048a8-6c09-11e8-9963-1d58c5e3c251.png)

O circulo roxo sinaliza a pergunta que está selecionada, as barras amarelas as que já foram respondidas e o troféu é um botão com a mesma função do "Finalizar" que só ativa quando tem o mínimo de perguntas respondidas.

Protótipo: https://marvelapp.com/6e384fb/screen/43225740
