### ISSUE TITLE
Definir categorias para as perguntas

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#41]
Atualmente todas estão na categoria chamada `categoria` :stuck_out_tongue:

**Comment by wab030** [comment]
Estou trabalhando nisso :-)

**Comment by notnotgabriel** [comment]
@wab030 quando tiver as categorias descreve pra gente aqui na issue por favor :)

**Comment by lguima** [comment]
Decidimos eliminar as categorias, pois ficou inviável para o @wab030 categorizar as perguntas de maneira equilibrada, uma categoria ficaria com muitas perguntas, outras, com menos.
