### ISSUE TITLE
Mover issues para repositórios especificos

### ISSUE THREAD

**Issue by notnotgabriel** [Minhacps/votasp#42]
Percebi que estamos discutindo algumas coisas especificas de outros repositórios neste aqui.
O que vocês acham de movermos as issues de discussoes sobre o App por exemplo, para o repositório votasp-app? O mesmo vale para backend e outros.

**Comment by victorperin** [comment]
Eu preferi fazer dessa maneira pelos seguintes motivos:
- Centralizar as issues em um único lugar. Assim é mais fácil do pessoal entender e ajudar os outros projetos caso haja necessidade.
- Grande parte das issues são relacionadas a mais de um projeto (Ex: backend e frontend), com isso podemos criar apenas uma issue compartilhada entre os 2 e o pessoal discutir em conjunto.
- Milestones funcionam melhor juntas do que quebra-las em cada projeto. As vezes um projeto terminou mas o outro não. O que mostraria a milestone em um dos projetos como completa.
- Fica mais fácil para pessoas que estão querendo ajudar o projeto mas não sabem muito bem por onde começar. Quando as coisas estão todas juntas, fica mais fácil de seguir.
- É possível linkar pull requests dos outros repositórios colocando algo do tipo minhacps/votasp-backend#1

Já as desvantagens de manter código em locais separados, que eu percebi:
- começaram a surgir issues duplicadas tanto no repo principal quanto no repo do projeto.
- Pessoas que usam pouco o git ou não entendem muito do projeto se sentem perdidas (Recebi esse feedback de algumas pessoas que convidei)

Mas eu queria a opinião de todo o @Minhacps/votasp-team sobre esse assunto. O que vocês acham? Quais problemas isso poderia causar? E quais vantagens podemos ter se separarmos essas issues.

**Comment by lguima** [comment]
Na organização [**Minhacps**](https://github.com/Minhacps) também é possível [criar projetos](https://github.com/orgs/Minhacps/projects), havia começado a criar, mas logo vocês já tocaram nesse aqui.

Eu, particularmente, nunca vi organização dessa maneira, centralizando as issues, sendo cada repositório uma aplicação individual, cada um deveria ter suas respectivas issues.

E essa funcionalidade de projetos do GitHub é bem crua, também não ajuda muito.

**Comment by victorperin** [comment]
Não sabia que dava para criar projetos na org. Pode ser uma alternativa para organizar as coisas.

Mas não acho que isso resolva as issues que se relacionam tanto com front-end e back-end.
Além disso, o problema com as milestones continua.

Eu conheço alguns projetos que centralizam as issues, mas acabam por não controlar dentro do github, mas por algum recurso externo.

Um exemplo é o projeto do [Keycloak](https://github.com/keycloak/keycloak/).
Sei que a google faz uma coisa parecida, mas usando bots para criar issues em um repositório centralizado, fechado deles. (Quando eles resolvem, é um bot que fecha e te responde com a resposta).

Além disso, existem alguns projetos que criam repositórios apenas para a centralização de issues, pode exemplo o [Crowdmap](https://github.com/ushahidi/crowdmap-issues).

Isso é uma pratica relativamente comum. Existe até documentação do próprio github de como fazer:
https://help.github.com/articles/creating-an-issues-only-repository/

**Comment by lguima** [comment]
Pelo que entendi, nenhum dos dois é o nosso caso. Não temos um controle externo ao GitHub, nem temos repositórios privados.

**Comment by victorperin** [comment]
Desculpa @lguima acho que me expressei de forma confusa.

A idéia é simplificar a visualização das issues para alguém que quer ajudar. Se uma issue se relaciona com o back-end e com o front-end, é saudavel que os 2 entendam e discutam o que estão fazendo. Separando em duas issues, para cada projeto, o front-end e o back-end podem não se conversar e implementar de maneiras diferentes.

Mas sério gente, se vocês acham que isso é ruim pro projeto, eu posso separar essas issues. Vai dar um certo trabalho a mas da pra fazer. Minha única preocupação é que vejos muitos projetos com problemas de issues duplicadas e isso era uma forma de resolver.

**Comment by notnotgabriel** [comment]
Concordo em manter já que está tudo centralizado aqui. É mais questão de costume mesmo.

**Comment by victorperin** [comment]
Beleza então gente.
Por enquanto vou fechar essa issue, mas quem quiser, fica a vontade de reabri-la para conversarmos.

Se realmente não tiver rolando, a gente muda as coisas aqui.

**Comment by victorperin** [comment]
E obrigado @lguima e @notnotgabriel, essas questões são realmente importantes para manter a simplicidade das coisas.
