### ISSUE TITLE
Menu no APP

### ISSUE THREAD

**Issue by mandyellow** [Minhacps/votasp#48]
Colocar um menu na barra fixa com Home (página inicial), Perfil/Editar Perfil, Ver resultado, Pesquisar candidatos e Sair

**Comment by notnotgabriel** [comment]
Duas duvidas:
Precisa ter perfil e edicao de perfil?
O ver resultado seria a pagina de ranking?

**Comment by mandyellow** [comment]
Perfil: Eu acredito que seja necessário talvez para candidatos para adicionar um campo de descrição/sobre/ quem sou eu. Mas isso é mais uma sugestão.

Resultado: sim, seria o ranking depois que já completou o número mínimo de respostas.
