### ISSUE TITLE
Complexidade página de perguntas: divergência app mobile e desktop 

### ISSUE THREAD

**Issue by mandyellow** [Minhacps/votasp#50]
Na página de perguntas, levantei aqui um ponto com o pessoal sobre a complexidade de desenvolvimento. Atualmente está:
1- Modelo desktop com todas as perguntas da categoria na mesma página (vide wireframe abaixo)
2- Modelo mobile com uma pergunta por página

@victorperin comentou que talvez seja mais fácil desenvolver o mobile com todas as perguntas na mesma página num primeiro momento e depois fazer os ajustes, o que vocês acham?

![screenshot_from_2018-05-22_09-09-42](https://user-images.githubusercontent.com/30158643/41193112-8f5066e4-6bde-11e8-8bda-f9487ae8ab26.png)

**Comment by victormiguez** [comment]
Concordo com o @victorperin, seria realmente mais simples se desktop e mobile seguissem o mesmo modelo pelo menos por enquanto.

**Comment by notnotgabriel** [comment]
É mais fácil até pra gente implementar se seguir o mesmo modelo o/

**Comment by lguima** [comment]
Neste caso, seguindo o _mobile first_, o ideal seria seguir com uma pergunta por tela.
