### ISSUE TITLE
Vulnerabilidades de pacotes

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votasp#51]
![image](https://user-images.githubusercontent.com/5847145/41194296-aa360778-6bef-11e8-86a8-a49a3bc56e02.png)

**Comment by victormiguez** [comment]
Posso olhar esse problema.

**Comment by notnotgabriel** [comment]
treta em?!

**Comment by victormiguez** [comment]
O problema foi corrigido durante o desenvolvimento, não temos mais alerta de vulnerabilidade.
