### ISSUE TITLE
Criar componente de busca de candidatos. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votasp#56]
O sistema deve ter um componente que busca um candidato pelo seu nome ou número. Caso o candidato não exista o sistema deve possibilitar o usuário enviar um e-mail para o candidato solicitando que ele/ela responda as questões.

**Comment by victorperin** [comment]
Acredito que isso seja uma coisa a se tratar no futuro. Após a execução do match.

**Comment by wab030** [comment]
Isso.
