### ISSUE TITLE
Problema de compartilhamento no Facebook.

### ISSUE THREAD

**Issue by sanvouza** [Minhacps/votasp#73]
1.  O título da página aparece como: "Só mais um site Wordpress.".
2. Não possui a opção de alteração da imagem de miniatura.

![img](https://user-images.githubusercontent.com/38250720/42225007-e49932ee-7eb1-11e8-98cb-9f7bfdb82d55.png)

**Comment by victorperin** [comment]
@guiluchesi da uma olhada na descrição do site, por favor.

**Comment by luchesigui** [comment]
Isso é só mudar lá no admin, ai vai do pessoal escrever uma descrição.
Pra mudar isso ta lá no Configurações > Geral
